### ISSUE TITLE
pretrained vgg16 model 

### ISSUE THREAD

**Issue by LH-mmm** [Machine-Listeners-Valencia/DCASE2021-Task1b#5]
Hi ! 
Can you provide the hdf5 file of the pre-trained VGG16 model on places365 ?

### pre_model = load_model('PATH_TO\vgg16_places_t2_1x.hdf5', compile=False) ###

Thanks!

**Comment by JNaranjo-Alcazar** [comment]
https://github.com/GKalliatakis/Keras-VGG16-places365
